apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://rancher.quantum-flow.tech/k8s/clusters/local"

users:
- name: "local"
  user:
    token: "kubeconfig-user-fls5ms52w4:648nlhj6gmr2c9pf7pwnzr4w7r766rhm2x477ph9nvqgz6htjlczfr"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
